### PR TITLE
Jane/7/configurable o us

### PR DESCRIPTION
**Pull request by jane-prowler**
Fixes issue #7

### CODE REVIEW

**Comment by ash2k** [comment]
Hey, thanks for the PR. Could you sign the CLA so that we can merge this? Changes look good to me.

**Comment by jane-prowler** [comment]
Thanks.  I'm just waiting on the company lawyers to okay my signing the CLA.

**Comment by jane-prowler** [comment]
CLA is now signed.

**Comment by ash2k** [comment]
Could you squash the commits before I merge? I'm not sure Github will preserve author if I use "squash and merge" merge mode.

**Review by ash2k — APPROVED** [review]

**Comment by jane-prowler** [comment]
Commits squashed.

**Comment by ash2k** [comment]
Thanks 👍

**Pull request merged**
